name: Basics
version: '${project.version}'
main: de.tomino.basics.Basics
api-version: 1.18
authors: [ TominoLP ]
description: a Plugin for for basic commands
website: https://github.com/TominoLP/Basics
commands:
  Gm:
    aliases:
      - gamemode
    description: change the gamemode of a player
    permission: basics.gm

  Tp:
    aliases:
      - tp
      - teleport
    description: teleport a player to another player
    permission: basics.tp

  TpHere:
    aliases:
      - tphere
      - teleporthere
    description: teleport a player to your location
    permission: basics.tphere

  TpHereAll:
    aliases:
      - tpall
      - teleportall
    description: teleport all players to your location
    permission: basics.tpall

  Heal:
    aliases:
      - heal
    description: heal a player
    permission: basics.heal

  HealAll:
    aliases:
      - healall
    description: heal all players
    permission: basics.healall

  EC:
    aliases:
      - ec
      -
      - enderchest
    description: open the economy menu
    permission: basics.ec

  Fly:
    aliases:
      - fly
    description: enable/disable fly mode
    permission: basics.fly

  FlySpeed:
    aliases:
      - flyspeed
      - fs
    description: set the fly speed
    permission: basics.flyspeed

  BlockBreakSwitch:
    aliases:
      - blockbreakswitch
      - bbs
    description: enable/disable block break
    permission: basics.blockbreak

  AdminGui:
    aliases:
      - admingui
      - ag
    description: open the admin gui
    permission: basics.admin

  AdminCms:
    aliases:
      - admincoms
      - ac
      - admin
    description: use admin commands
    permission: basics.admincoms

  Day:
    aliases:
      - day
    description: set the time to day
    permission: basics.time

  Night:
    aliases:
      - night
    description: set the time to night
    permission: basics.time

  Midnight:
    aliases:
      - midnight
    description: set the time to midnight
    permission: basics.time

  Noon:
    aliases:
      - noon
    description: set the time to noon
    permission: basics.time

  Sunrise:
    aliases:
      - sunrise
    description: set the time to sunrise
    permission: basics.time

  Sunset:
    aliases:
      - sunset
    description: set the time to sunset
    permission: basics.time



