name: Basics
version: '${project.version}'
main: de.tomino.basics.Basics
api-version: 1.18
authors: [ TominoLP ]
description: a Plugin for for basic commands
website: https://github.com/TominoLP/Basics
commands:
  Gm:
    aliases:
      - gamemode
    description: change the gamemode of a player
    permission: basics.gm

  Tp:
    aliases:
      - tp
      - teleport
    description: teleport a player to another player
    permission: basics.tp

  TpHere:
    aliases:
      - tphere
      - teleporthere
    description: teleport a playerto your location
    permission: basics.tphere

  TpHereAll:
    aliases:
      - tpall
      - teleportall
    description: teleport all players to your location
    permission: basics.tpall

  Heal:
    aliases:
      - heal
    description: heal a player
    permission: basics.heal

  HealAll:
    aliases:
      - healall
    description: heal all players
    permission: basics.healall

  EC:
    aliases:
      - ec
      -
      - enderchest
    description: open the economy menu
    permission: basics.ec

  Fly:
    aliases:
      - fly
    description: enable/disable fly mode
    permission: basics.fly

  FlySpeed:
    aliases:
      - flyspeed
      - fs
    description: set the fly speed
    permission: basics.flyspeed



