name: Basics
version: '${project.version}'
main: de.tomino.basics.Basics
api-version: 1.18
authors: [ TominoLP ]
description: a Plugin for for basic commands
website: https://github.com/TominoLP/Basics
commands:
  gm:
    aliases:
      - gamemode
    description: change the gamemode of a player
    permission: basics.gm


